name: build-wheels
description: Build Slicer Core and Slicer Core SDK for a given platform

on:
  workflow_call:
    inputs:
      os:
        description: 'The operating system to run the job on'
        required: true
        type: string
      vtk-tag:
        description: 'VTK version to use, must match the one in pyproject.toml'
        required: true
        type: string
      build-target:
        description: 'CIBW build target (e.g., cp310-manylinux_x86_64)'
        required: true
        type: string
      python-version:
        description: 'CIBW build target (e.g., 3.10)'
        required: true
        type: string
      platform-tag:
        description: 'Wheel platform tag to apply after building. Ignored on Windows.'
        required: true
        type: string
      use-cache:
        description: 'Enable or disable ccache restoration and saving'
        type: boolean
        default: true
        required: true
      dry-run:
        description: 'Creates a dummy wheel instead of building slicer core'
        type: boolean
        default: false
        required: false

jobs:
  build-windows-latest:
    if: ${{ inputs.os == 'windows-latest' }}
    uses: ./.github/workflows/build-wheels-windows.yml
    with:
      vtk-tag: ${{ inputs.vtk-tag }}
      python-version: ${{ inputs.python-version }}
      use-cache: true
    
  build-ubuntu-latest:
    if: ${{ inputs.os == 'ubuntu-latest' }}
    uses: ./.github/workflows/build-wheels-linux.yml
    with:
      vtk-tag: ${{ inputs.vtk-tag }}
      build-target: ${{ inputs.build-target }}
      python-version: ${{ inputs.python-version }}
      platform-tag: ${{ inputs.platform-tag }}
      use-cache: true
  
  build-macos-15:
    if: ${{ inputs.os == 'macos-15' }}
    uses: ./.github/workflows/build-wheels-mac.yml
    with:
      vtk-tag: ${{ inputs.vtk-tag }}
      python-version: ${{ inputs.python-version }}
      use-cache: true
